org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)
forge_version=47.1.44
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.06.26-1.20.1
license=LGPL-3.0

archive_base_name=nfulib-1.20.1
jei_version=15.2.0.27
mixinextras_version=0.3.1
mixinextras_min_version=0.3.0

mod_id=nfulib
group_id=net.sodiumzh.nfu
mod_authors=SodiumZH

mod_version=0.2.32
filename_version=0.2.32-dev
mod_name=NFU Library
mod_group_id=net.sodiumzh.nfu
mod_license=LGPL-3.0
mod_description=Natrium Forge Utilities - miscellaneous utilities for Forge game mechanics.