org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false
minecraft_version=1.18.2
minecraft_version_range=[1.18.2,1.19)
forge_version=40.2.4
forge_version_range=[40,)
loader_version_range=[40,)
mapping_channel=parchment
mapping_version=2022.08.07-1.18.2
license=LGPL-3.0

archive_base_name=nfulib-1.18.2
jei_version=9.7.0.194
mixinextras_version=0.3.1
mixinextras_min_version=0.3.0

mod_id=nfulib
group_id=net.sodiumzh.nfu
mod_authors=SodiumZH

mod_version=0.0.33
filename_version=0.0.33
mod_name=NFU Library
mod_group_id=net.sodiumzh.nfu
mod_license=LGPL-3.0
mod_description=Natrium Forge Utilities - miscellaneous utilities for Forge game mechanics.