org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false

# Parchment mappings. See https://parchmentmc.org/docs/getting-started
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.248
neo_version_range=[21.1,)
loader_version_range=[1,)
license=LGPL-3.0

archive_base_name=nfulib-1.21.1
jei_version=19.44.0.401
mixinextras_version=0.5.4

mod_id=nfulib
group_id=net.sodiumzh.nfu
mod_authors=SodiumZH

mod_version=0.2.33
filename_version=0.2.33-snapshot-260819a
mod_name=NFU Library
mod_group_id=net.sodiumzh.nfu
mod_license=LGPL-3.0
mod_description=Natrium Forge Utilities - miscellaneous utilities for Forge game mechanics.