modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}"
license="LGPL-3.0"
issueTrackerURL="https://github.com/SodiumZH/NFU_Library"

[[mods]]
modId="${nfu_mod_id}"
version="${nfu_version}"
displayName="${nfu_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/nfu_library"
#credits="SodiumZH"
authors="${nfu_authors}"
description="${nfu_description}"

[[dependencies.${nfu_mod_id}]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.${nfu_mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
