modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}"
license="LGPL-3.0"
issueTrackerURL="https://github.com/SodiumZH/NFU_Library"

[[mods]]
modId="${nfu_mod_id}"
version="${nfu_version}"
displayName="${nfu_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/nfu_library"
#credits="SodiumZH"
authors="${nfu_authors}"
description="${nfu_description}"

# The [[mixins]] block allows you to declare your mixin config to FML so that it gets loaded.
[[mixins]]
config="nfulib.mixins.json"

[[dependencies.${nfu_mod_id}]] #optional
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="${neo_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.${nfu_mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
