package net.sodiumzh.nfu.entity.component;

import net.minecraft.world.entity.Entity;
import net.sodiumzh.nfu.util.NFUDebugStatics;

import java.util.List;
import java.util.Set;

/**
 * NFU Entity Component API
 * ------------------------
 *
 * This class provides the primary entrypoints to the NFU Entity Component System, a flexible, hierarchical ECS (Entity-Component System)
 * for Minecraft entities built upon the Forge Capability framework.
 *
 * **Overview:**
 * - The API enables attaching, navigating, and managing complex trees of modular components on any Minecraft entity.
 * - Each entity has exactly one {@link CEntityComponentManager}, serving as the root for its component tree and handling ticking, serialization, and requirement checks for all descendants.
 * - Components can store arbitrary data, provide logic (such as timers or dynamic NBT), and declare required subcomponents.
 * - The system ensures type-safe attachment (components specify their required entity class), prevents cycles, and supports both server-side and client-side component trees.
 * - Default (built-in) components such as dynamic data and timers are automatically provided, but the system is fully extensible for custom components.
 *
 * **Key Capabilities:**
 * - Retrieve the component manager for any entity (with safe fallback and debug logging if missing).
 * - Access specific default components (dynamic data and timer) by type-safe key.
 * - Traverse and manipulate the component tree through path-based and type-based methods.
 * - Synchronize data on demand via custom code; state is *not* auto-synchronized between server and client.
 *
 * **Usage Examples:**
 *   EntityComponentAPI.getComponentManager(entity)      // Access a root component manager (or creates a fallback)
 *   EntityComponentAPI.getDynamicDataComponent(entity)  // Access the entity's dynamic data component
 *   EntityComponentAPI.getDefaultTimer(entity)          // Access the default timer component
 *
 * Advanced users can build their own component hierarchies by implementing or extending custom components, declaring required components, and attaching logic as needed.
 *
 * For details, see the contracts and examples on {@link IEntityComponent}, {@link CEntityComponentManager}, and {@link EntityComponentBase}.
 * #Comments generated by GitHub Copilot
 */
public class EntityComponentAPI {

    public static CEntityComponentManager getComponentManager(Entity e) {
        return e.getCapability(EntityComponentStatics.CAP_MANAGER).orElseGet(() -> {
            NFUDebugStatics.errorOnce(EntityComponentAPI.class, String.format("Entity \"%s\" missing component manager. " +
                    "If the entity is pending removal, this message can be ignored.", e.getName().getString()));
            return new CEntityComponentManagerImpl(e);
        });
    }

    public static EntityDynamicDataComponent<Entity> getDynamicDataComponent(Entity e) {
        return getComponentManager(e).getSubComponent("dynamic_data", EntityComponentTypes.DYNAMIC_DATA.get()).orElseGet(() -> {
            NFUDebugStatics.errorOnce(EntityComponentAPI.class, String.format("Entity \"%s\" missing dynamic data component. " +
                    "If the entity is pending removal, this message can be ignored.", e.getName().getString()));
            return new EntityDynamicDataComponent<>(e);
        });
    }

    public static EntityTimerComponent<Entity> getDefaultTimer(Entity e) {
        return getComponentManager(e).getSubComponent("default_timer", EntityComponentTypes.DEFAULT_TIMER.get()).orElseGet(() -> {
            NFUDebugStatics.errorOnce(EntityComponentAPI.class, String.format("Entity \"%s\" missing default timer component. " +
                    "If the entity is pending removal, this message can be ignored.", e.getName().getString()));
            return new EntityTimerComponent<>(e);
        });
    }

    public static Set<IEntityComponent<? extends Entity>> getAllComponents(Entity target) {
        return getComponentManager(target).getSelfAndDownstreamComponents();
    }
}
