package net.sodiumzh.nfu.entity.component;

import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.LivingEntity;
import net.sodiumzh.nfu.entity.component.preset.EntityAttributeMonitorComponent;
import net.sodiumzh.nfu.entity.component.preset.EntityDataComponent;
import net.sodiumzh.nfu.entity.component.preset.EntitySyncherComponent;
import net.sodiumzh.nfu.entity.component.preset.EntityTimerComponent;
import net.sodiumzh.nfu.object.HierarchyPath;
import net.sodiumzh.nfu.util.NFUDebugStatics;

import java.util.Optional;
import java.util.Set;

/**
 * NFU Entity Component API
 * ------------------------
 *
 * This class provides the primary entrypoints to the NFU Entity Component System, a flexible, hierarchical ECS (Entity-Component System)
 * for Minecraft entities built upon the Forge Capability framework.
 *
 * **Overview:**
 * - The API enables attaching, navigating, and managing complex trees of modular components on any Minecraft entity.
 * - Each entity has exactly one {@link CEntityComponentManager}, serving as the root for its component tree and handling ticking, serialization, and requirement checks for all descendants.
 * - Components can store arbitrary data, provide logic (such as timers or dynamic NBT), and declare required subcomponents.
 * - The system ensures type-safe attachment (components specify their required entity class), prevents cycles, and supports both server-side and client-side component trees.
 * - Default (built-in) components such as dynamic data and timers are automatically provided, but the system is fully extensible for custom components.
 *
 * **Key Capabilities:**
 * - Retrieve the component manager for any entity (with safe fallback and debug logging if missing).
 * - Access specific default components (dynamic data and timer) by type-safe key.
 * - Traverse and manipulate the component tree through path-based and type-based methods.
 * - Synchronize data on demand via custom code; state is *not* auto-synchronized between server and client.
 *
 * **Usage Examples:**
 *   EntityComponentAPI.getComponentManager(entity)      // Access a root component manager (or creates a fallback)
 *   EntityComponentAPI.getDynamicDataComponent(entity)  // Access the entity's dynamic data component
 *   EntityComponentAPI.getDefaultTimer(entity)          // Access the default timer component
 *
 * Advanced users can build their own component hierarchies by implementing or extending custom components, declaring required components, and attaching logic as needed.
 *
 * For details, see the contracts and examples on {@link IEntityComponent}, {@link CEntityComponentManager}, and {@link EntityComponentBase}.
 * #Comments generated by GitHub Copilot
 */
public class EntityComponentAPI {

    /**
     * Get the component manager if present. Called when you must specially handle cases of absence (e.g in the entity construction process).
     * For general usage, use {@code getComponentManager()}.
     */
    public static Optional<CEntityComponentManager> getComponentManagerOptional(Entity e) {
        return e.getCapability(EntityComponentStatics.CAP_MANAGER).resolve();
    }

    public static CEntityComponentManager getComponentManager(Entity e) {
        return e.getCapability(EntityComponentStatics.CAP_MANAGER).orElseGet(() -> {
            if (e.isAlive())
                NFUDebugStatics.errorOnce(EntityComponentAPI.class, String.format("Entity \"%s\" missing component manager. " +
                    "If the entity is pending removal, this message can be ignored.", e.getName().getString()));
            return new EntityComponentManagerPlaceholder(e);
        });
    }

    public static EntityDataComponent<Entity> getDataComponent(Entity e) {
        return getComponentManager(e).getSubComponent("dynamic_data", EntityComponentTypes.DATA.get()).orElseGet(() -> {
            if (e.isAlive())
                NFUDebugStatics.errorOnce(EntityComponentAPI.class, String.format("Entity \"%s\" missing dynamic data component. " +
                    "If the entity is pending removal, this message can be ignored.", e.getName().getString()));
            return EntityComponentTypes.DATA.get().create(e);
        });
    }

    public static EntityTimerComponent<Entity> getDefaultTimer(Entity e) {
        return getComponentManager(e).getSubComponent("timer", EntityComponentTypes.TIMER.get()).orElseGet(() -> {
            if (e.isAlive())
                NFUDebugStatics.errorOnce(EntityComponentAPI.class, String.format("Entity \"%s\" missing default timer component. " +
                    "If the entity is pending removal, this message can be ignored.", e.getName().getString()));
            return EntityComponentTypes.TIMER.get().create(e);
        });
    }

    public static EntitySyncherComponent<Entity> getDefaultSyncher(Entity e) {
        return getComponentManager(e).getSubComponent("syncher", EntityComponentTypes.SYNCHER.get()).orElseGet(() -> {
            if (e.isAlive())
                NFUDebugStatics.errorOnce(EntityComponentAPI.class, String.format("Entity \"%s\" missing default timer component. " +
                "If the entity is pending removal, this message can be ignored.", e.getName().getString()));
            return EntityComponentTypes.SYNCHER.get().create(e);
        });
    }

    public static EntityAttributeMonitorComponent getAttributeMonitor(LivingEntity e) {
        return getComponentByPathOrFallback(e, HierarchyPath.byNameArray("attribute_monitor"), EntityComponentTypes.ATTRIBUTE_MONITOR.get());
    }

    public static Optional<IEntityComponent<? extends Entity>> getComponentByPath(Entity e, HierarchyPath path) {
        return getComponentManager(e).getSubComponentByPath(path);
    }

    public static Optional<IEntityComponent<? extends Entity>> getComponentByPath(Entity e, String path) {
        return getComponentManager(e).getSubComponentByPath(HierarchyPath.byLiteral(path));
    }

    public static <T extends IEntityComponent<? extends Entity>> Optional<T> getComponentByPath(Entity e, HierarchyPath path, EntityComponentType<?, T> type) {
        return getComponentManager(e).getSubComponentByPath(path, type);
    }

    public static <T extends IEntityComponent<? extends Entity>> Optional<T> getComponentByPath(Entity e, String path, EntityComponentType<?, T> type) {
        return getComponentByPath(e, HierarchyPath.byLiteral(path), type);
    }

    public static <T extends IEntityComponent<? extends Entity>> Optional<T> getComponentByPath(Entity e, SubComponentAccessor<? extends Entity, T> accessor) {
        return getComponentManager(e).getSubComponentByPath(accessor);
    }

    public static Set<IEntityComponent<? extends Entity>> getAllComponents(Entity target) {
        return getComponentManager(target).getSelfAndDownstreamComponents();
    }

    /**
     * Get a component of an entity by path, or create a transient default component as fallback.
     * <p>Note: the fallback only works as a placeholder, and will not be attached to the entity.
     */
    public static <T extends IEntityComponent<? extends Entity>> T getComponentByPathOrFallback(Entity e, HierarchyPath path, EntityComponentType<?, T> type) {
        return getComponentByPath(e, path, type).orElseGet(() -> type.createUnsafe(e));
    }

    /**
     * Get a component of an entity by accessor, or create a transient default component as fallback.
     * <p>Note: the fallback only works as a placeholder, and will not be attached to the entity.
     */
    public static <T extends IEntityComponent<? extends Entity>> T getComponentByPathOrFallback(Entity e, SubComponentAccessor<? extends Entity, T> accessor) {
        return getComponentByPathOrFallback(e, accessor.getPath(), accessor.getType());
    }

    /**
     * Get a component of an entity by path, or create a transient default component as fallback.
     * <p>Note: the fallback only works as a placeholder, and will not be attached to the entity.
     */
    public static <T extends IEntityComponent<? extends Entity>> T getComponentByPathOrFallback(Entity e, String path, EntityComponentType<?, T> type) {
        return getComponentByPathOrFallback(e, HierarchyPath.byLiteral(path), type);
    }

    /**
     * Quick check if a component's path in the component manager is the given path.
     */
    public static boolean pathInManagerEquals(IEntityComponent<?> test, HierarchyPath path) {
        return getComponentByPath(test.getEntity(), path).filter(c -> c == test).isPresent();
    }

    /**
     * Quick check if a component's path in the component manager is the given path.
     */
    public static boolean pathInManagerEquals(IEntityComponent<?> test, String path) {
        return getComponentByPath(test.getEntity(), path).filter(c -> c == test).isPresent();
    }

}
